linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused

linters-settings:
  errcheck:
    check-type-assertions: true

issues:
  exclude-rules:
    - linters:
        - staticcheck
      text: "SA1019:"
  max-issues-per-linter: 0
  max-same-issues: 0
